# Site wide configuration

title: Kevin Waweru
description: "Business development is fun"
logo: 120x120.gif
teaser: 400x250.gif
locale: en_US
disqus-shortname: kevinwaweru
url: ''

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:title/
kramdown:
  toc_levels: 1..2
highlighter: pygments
gems:
  - jekyll-sitemap
paginate: 5
paginate_path: "page-:num"

# Site owner
owner:
  name: Kevin Waweru
  web: http://kevinwaweru.com
  email: k.waweru1@gmail.com
  twitter: 
  bio: "Business developer, I develop, write, test and deploy software/business solutions."
  avatar: bio-photo.jpg # 160x160 px image for author byline
  google:
    plus: 
    ad-client: 
    ad-slot: 
  disqus-shortname:

# Settings for analytics helper
# Set 'provider' to the analytics provider you want to use.
# Set 'provider' to false to turn analytics off globally.
#
analytics :
  provider : google
  google :
      tracking_id : 
  getclicky :
    site_id :


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
